### PR TITLE
NeW uPdAtE

### PR DESCRIPTION
**Pull request by ApfelTV**
~~can i kill myself now~~

### CODE REVIEW

**Comment by DarkPhoenix10** [comment]
does apfel even know hau 2 open sauce smh

**Comment by ApfelTV** [comment]
what

**Comment by DarkPhoenix10** [comment]
because of what happened in the previous pull requests you stinky xddd

**Comment by DarkPhoenix10** [comment]
j

**Comment by ApfelTV** [comment]
oof

**Comment by DarkPhoenix10** [comment]
foo

**Comment by ApfelTV** [comment]
i sat 20 min around to get this thing ready and its still not accepted :c

**Comment by ApfelTV** [comment]
ThIs UpDaTe Is So NeW tHo

**Comment by ApfelTV** [comment]
when does this get merged

**Comment by Artuto** [comment]
XDDDDD

**Comment by FroskPL** [comment]
Lmao

**Comment by ApfelTV** [comment]
aRe YoU kIdDiNg Me U bAdBoI

**Comment by Alej0hio** [comment]
so many apples

**Pull request closed without merging**
