### PR TITLE
Coolest update ever seen

### PR DESCRIPTION
**Pull request by ApfelTV**
- Removed unnecessairy files
- Modded code
- Windows Version doesnt need admin perms anymore

~~when do i get my dev role~~ jk

### CODE REVIEW

**Comment by Artuto** [comment]
Again, why did you deleted files in the .github folder?

They are used for PRs and Issues.

**Comment by ApfelTV** [comment]
No one uses them

**Comment by ApfelTV** [comment]
~~And PokeAcer created them, so they are satan~~

**Comment by Artuto** [comment]
yeah, they are there for a reason. So you should re-create them

**Comment by KcrPL** [comment]
Bye bye

**Comment by ApfelTV** [comment]
are you kidding me

**Comment by sks316** [comment]
Yes. 
Now recreate the files or you aren't getting accepted.

**Pull request closed without merging**
