### PR TITLE
some grammar fixes

### PR DESCRIPTION
**Pull request by DismissedGuy**
Corrected some grammar mistakes and added some spaces here and there to make it look (imo) a bit cleaner. I had to split the contact email line on startup and make some text borders a bit longer because it didn't fit, but I _think_ it's all righty now.

Feel free to edit if you disagree with the whitespaces.

### CODE REVIEW

**Comment by KcrPL** [comment]
I'm thinking about releasing it as 2,1.7 or 2.1.6-Update1. 

Anyway, good job. Thank you very much.
I don't have time now but I'll work on it tommorow.

**Comment by Artuto** [comment]
Why always dismissed's PRs get forgotten

**Comment by Apfel** [comment]
They get **dismissed**

**Comment by DismissedGuy** [comment]
I'm guessing that the patcher has evolved to a point where this PR isn't usable anymore, just like with Endless

Rip all those tedious hours of work I have spent during several midnights to deliver my precious handcrafted string edits :(

**Pull request closed without merging**
